### ISSUE TITLE
multi send multi message

### ISSUE THREAD

**Issue by tarikogut** [infobip/oneapi-php#10]
how to send multi number multi send

for example 

message: test1 
gsm : 90123456745
message: test1 
gsm : 90123456745

**Comment by anamarjanovic** [comment]
Hello tarikogut,

You can send a message with the same text to multiple numbers like this:

```
$smsMessage = new SMSRequest();
$smsMessage->senderAddress = SENDER_ADDRESS;
$smsMessage->address = '90123456745,90123456746,90123456747';
$smsMessage->message = 'Hello world';
```

If you want to send different message text, you will have to make another SMSRequest.


```
$smsMessage1 = new SMSRequest();
$smsMessage1->senderAddress = SENDER_ADDRESS;
$smsMessage1->address = '90123456745,90123456746,90123456747';
$smsMessage1->message = 'Text 1';


$smsMessage2 = new SMSRequest();
$smsMessage2->senderAddress = SENDER_ADDRESS;
$smsMessage2->address = '90123456748,90123456749';
$smsMessage2->message = 'Text 2';
```

**Comment by tarikogut** [comment]
which version ?

**Comment by anamarjanovic** [comment]
If you are not using composer, switch to `0.0.3-alpha` branch.
In case you are using composer, you can use the latest version `1.1.3` on master branch.

**Comment by tarikogut** [comment]
only working single submit many numbers


2015-03-09 10:57 GMT+02:00 Ana Marjanovic <notifications@github.com>:

**Comment by maricn** [comment]
Would you please explain this in detail? What is not working?
