### ISSUE TITLE
Return of sendMessageResults in method sendSMS

### ISSUE THREAD

**Issue by willjosefi** [infobip/oneapi-php#11]
Hello.

Recently i have a big problem with SendMessageResult[messageStatus], for default, php class don't return this result.

I have made a change in models/ResourceReference for this works... But i don't know if it is the better way to solve this problem.

```php
<?php

namespace infobip\models;
use infobip\Models;
use infobip\SubscriptionIdFieldConversionRule;
use infobip\SubFieldConversionRule;

/**
 * Resulting object on message (HLR/LBS) send.
 */
class ResourceReference extends AbstractObject {

    /**
     * The client correlator for this message. This value may be used to query
     * for message status later.
     */
    public $clientCorrelator;

    /**
     * Status
     */
    public $messageStatus;

    public function __construct($array=null, $success=true) {
        parent::__construct($array, $success);
    }

}

Models::register(
    'infobip\models\ResourceReference',
    array(
        new SubscriptionIdFieldConversionRule('clientCorrelator', 'resourceReference.resourceURL'),
        new SubFieldConversionRule('messageStatus', 'sendMessageResults.0.messageStatus'),
    )
);

?>
```

**Comment by mmilakovic** [comment]
Hi,

Your solution is ok if you are sending one message to one destination. 
But it can be done in other ways:

1) You can use ```clientCorrelator``` value to retrieve deliveryInfos of sent messages. You will get information about message status when you call that method. You can see example how to call this method [here](https://github.com/infobip/oneapi-php/blob/master/examples/send_message.php).

2) You can make new model ```SendMessageResults``` which will have ```messageStatus``` field in the class. Also you can add other available information. List of available information can be found [here](http://developer.infobip.com/api#!/SendSMS/POST_1_smsmessaging_outbound_senderAddress_requests)

We are staying at your disposal for any additional questions.

Kind regards,
Milos
