### ISSUE TITLE
Is it possible to use schedule?

### ISSUE THREAD

**Issue by stnw** [infobip/oneapi-php#12]
Hello!
I've found this future in API, but can't find in the library:
http://dev.infobip.com/docs/schedule-sms

Thanks!

**Comment by maricn** [comment]
Hi stnw,

This repository (oneapi-php) is related to deprecated HTTP API. We are planning to release new PHP library that will use current API (the one described on your link - http://dev.infobip.com) soon.

**Comment by enenemultimedia** [comment]
Hello,

How do I schedule an SMS using the new php API?
I have looked all over the internet for this and the documentation on the dev.infobip.com shows that of json alone.
Thanks
