### ISSUE TITLE
SMS types?

### ISSUE THREAD

**Issue by thanosalexander** [infobip/oneapi-php#13]
Hello.I use this client on my laravel application..all work nice but I think you forgot to include types to SMS..Now there is only Text SMS support,but where is the binary,flash and WAP push support. But  on https://dev.infobip.com there is support!

**Comment by nmenkovic-ib** [comment]
Hi,

This is the legacy library and it doesn't support all the functionalities from https://dev.infobip.com. 
If you want to send binary or flash SMS, you should use https://github.com/infobip/infobip-api-php-client, as it covers all SMS API features.

Kind regards,
Nevena
