### ISSUE TITLE
SENDER_ADDRESS returns DeliveryImpossible when alphanumeric characters are used

### ISSUE THREAD

**Issue by leyluj** [infobip/oneapi-php#7]
Hello?

Coding is stuff, but the php api return DeliveryImpossible when aphanumeric characters are used in the SENDER_ADDRESS 

Thanks.

**Comment by anamarjanovic** [comment]
Hi Leyluj,

DeliveryImpossible response is probably related to your Infobip account, not to oneapi-php library.
Could you please contact support@infobip.com with your account details, they will be able to assist you with this issue.

Kind regards
