### ISSUE TITLE
Support of unicode

### ISSUE THREAD

**Issue by stnw** [infobip/oneapi-php#9]
Hi!
I need to send SMS in Russian language. But if I understood correctly, I can't do it. So, I tried to set the parameter "dataCoding", but it looks like I can't do it too. 
If there any possibility to send a message with unicode support?
Thanks!

**Comment by mmiroslav** [comment]
Hi Sergey,

Just send message with Russian characters and it works. Here is the snippet:  

    <?php
    require_once __DIR__ . '/vendor/autoload.php';

    use infobip\models\SMSRequest;
    use infobip\SmsClient;
    use infobip\utils\Logs;

    $smsClient = new SmsClient('<USERNAME>', '<PASSWORD>');
    $smsClient->login();

    $smsMessage = new SMSRequest();
    $smsMessage->senderAddress = "<SENDER>";
    $smsMessage->address = "<PHONE-NUMBER>";
    $smsMessage->message = 'Калинка, калинка, калинка моя! В саду ягода малинка, малинка моя!';

    $smsMessageSendResult = $smsClient->sendSMS($smsMessage);

Could you, please, provide us more information about error that you get?

**Comment by stnw** [comment]
Hi, @mmiroslav !
Sorry for bothering. 
Looks. like I did something wrong. Now it works. 
Thank you!
